### ISSUE TITLE
About aliases.go

### ISSUE THREAD

**Issue by mcaci** [ECL2022PAI01/splunk-service#22]
In general in Go you don't have a separate constants or package variables file.

Generally it's best to declare constants just in the file(s) they are needed. If they are used in several places they can be exported to be able to reassign them or copy/pasted (the latter if only used in a few places)

For package variables it's way better that you pass them around as function parameters (separately or as part of a struct) but not left them as package variables. I have seen some usages for them and it can get tricky to use them. For this I would suggest you to define local variables in their place where they start to be defined and then pass them around to the functions where they are needed.
This may be difficult to do but will improve the readability of the library a lot.

**Comment by kuro-jojo** [comment]
The goal here was to be able to overwrite certain functions used in the tests.
For example `var cloudEventListener = CloudEventListener` wait and listen to an event and it is called by the main function. To test the main function, we overwrite the variable cloudEventListener by creating a fake listener function which close after few moment.

**Comment by mcaci** [comment]
I see your objective, for this I would still suggest to move the `var cloudEventListener = CloudEventListener` line just before `main()` to see immediately that it's used there and then look for it in the `main_test.go` function. In the end you have to look this variable up in two files rather than three.

Then I'm not used to write tests for main.go. In general in Go it's good to have main.go to be as minimal as possible so that all the code executed by `main()` func is tested in their own package.
In general but not for all cases, the more code is outside the main.go the easier you can test it.

**Comment by kuro-jojo** [comment]
That sounds like a better idea I think. We'll try it and see if everything works well
