### ISSUE TITLE
Some suggestions for main.go

### ISSUE THREAD

**Issue by mcaci** [ECL2022PAI01/splunk-service#30]
Hi everyone,

I'm summarizing some specific Go tips that you can use for main.go:

**line 36**: `var pollingSystemHasBeenStarted = false` => `var pollingSystemHasBeenStarted bool`
Every var is automatically assigned a value (see [docs](https://go.dev/tour/basics/12)) if not done explicitly.
I mean, I can understand the idea of making the value explicit but a Go programmer in general should understand without ambiguity that `var pollingSystemHasBeenStarted bool` 's value is false.

And generally, more for reflection, think about the way you could include those vars inside functions and pass them around to the code and the tests instead of putting them as package variables (the equivalent of globals in Go). In general, if possible, it's better to avoid package variables as they give issues for readability.

On a specific note I see you're not using anymore the vars in lines 170-173 in other files, so you can remove them.

**line 46**: logger.Errorf("Got Data Error: %s", err.Error()) => logger.Errorf("Got Data Error: %v", err)
This applies not only in this line but in any of your code where you have a *f function (Printf, Logf, Fatalf, Errorf and so on) and an error variable. You can use `%v` (prints the value of a variable) for the formatting verb and `err` as value without the need to invoke the Error() method.
Example here: https://play.golang.com/p/g3W0wGIOQI2

EXCEPT, if you are creating an error with `fmt.Errorf` and including an error: use `%w` (error wrapping) instead of any other formatting verb. Which comes as an example in following tip:
**line 81**: return errors.New("Could not create Keptn Handler: " + err.Error()) => return fmt.Errorf("Could not create Keptn Handler: %w", err)

**line 128-160**:
2 things here: (1) add a variable declaration in the switch statement e.g. `switch eType := event.Type()`; (2) use that variable in a default statement containing what is there in line 157-160, which is also a place where the two previous suggestion apply.

**line 199-207**

Generally in Go it is common to write code with the objective of reducing the indentation levels and putting all of the instruction for the "happy path" aligned on the leftmost side

Which means that this section:

```go
if strings.HasSuffix(alert.Name, handler.KeptnSuffix) {
	go func() {
		logger.Info("Start polling for triggered alerts ...")
		alerts.FiringAlertsPoll(splunkClient, nil, keptnOptions, env)
	}()
	pollingSystemHasBeenStarted = true
	break
}
```

becomes like this:

```go
if !strings.HasSuffix(alert.Name, handler.KeptnSuffix) {
	continue
}
go func() {
	logger.Info("Start polling for triggered alerts ...")
	alerts.FiringAlertsPoll(splunkClient, nil, keptnOptions, env)
}()
pollingSystemHasBeenStarted = true
```

**line 217**

In Go it's [preferred](https://go.dev/doc/effective_go#switch) to use switch instead of if/else.

So this:

```go
if env.Env == "local" {
	// ...
} else {
	// ...
}
```

would become this

```go
switch env.Env {
  case "local":
	// ...
  default:
	// ...
}
```

**lines 210 and 245,249,254**

Here is suggest to remove `os.Exit` wrapping `cloudEventListener` call and return nothing in that function because the log.Fatal calls, in lines 245 and 249, are calls to write a log line followed by os.Exit(1) and when you exit from main you exit with 0 automatically so there's no need to call `os.Exit`.

**Comment by Mouhamadou305** [comment]
Hi Michele, 
The issues have been fixed except for : 

Main : env, keptnOptions, SplunkClient and pollingSystemHasBeenSarted global variables can't be removed beacause they cannot be passed as parameters to ProcessKeptnCloudEvent function. This function should have a default signature in order to be callable in the SartReceiver call inside the CloudEventListener function.

Main : processKeptnCloudEvent, handleConfigureMonitoringTriggeredEvent and handleGetSliTriggeredEvent global variables can't be removed beacause they are still used in order to be able to mock the corresponding functions in our tests.

Configure_monitoring_event_handler : createAlert  is still used in order to be able to mock the corresponding function in our tests

**Comment by mcaci** [comment]
Ok, thanks for the explanations. We'll go with the PR that you submitted
